### ISSUE TITLE
Npm test failed.

### ISSUE THREAD

**Issue by Gowebbi-Dev** [heyman333/react-native-responsive-fontSize#42]
```
node_modules/react-native-responsive-fontsize/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { isIphoneX } from "react-native-iphone-x-helper";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React from 'react';
      2 | import {Text} from 'react-native';
    > 3 | import {RFPercentage} from 'react-native-responsive-fontsize';
        | ^
      4 |
      5 | const ResponsiveText = props => {
      6 |   return (

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/components/ResponsiveText.js:3:1)

```

**Comment by heyman333** [comment]
we have no test code

**Comment by victorjordan95** [comment]
I'm having this trouble too, in order to test my component that uses responsive-fontsize. Did you make it works?
